export const ActionTypes = {
    ADD_MARKER: "ADD_MARKER",
    SET_LOCATIONS: "SET_LOCATIONS",
    SET_POLYGONS: "SET_POLYGONS",
    ADD_POLYGONS: "ADD_POLYGONS",
    DELETE_POLYGON: "DELETE_POLYGON",
    DELETE_MARKER: "DELETE_MARKER"
} 
